### ISSUE TITLE
Small UI Features / Improvements

### ISSUE THREAD

**Issue by tgxn** [tgxn/lemmy-modder#32]
just a dump of issues I've seen and can't be bothered making new issues for them all since they are quite small.
I'll link them to issues where they have been created

## General
- [x] loading indicator must show site loading-state #99
- accounts picker
  - [x] click away from menu should close the menu...
  - [x] should have details on current user (community, avatar, role, etc)
  - [x] better management of unique id usage, as currently id's can conflict cross-site (in the tanstack query keys)

## Reports
- [x] reduce amount of api calls when dealing with content
- [x] update to nicer confirm buttons
- [x] list the community name it's in
- store/share data #60
  - [ ] "ignore for me" option (if you don't want to/can't deal with it)
  - [ ] "not site-wide role breaking" in case need have answer from community rules..
- [x] List the user who actioned the content report #75
- [x] #90
  - [ ] "Canned" Reply/Distinguish Comments #46
  - [ ] "Canned" Ban/Remove Reasons 
- [x] #87
- [x] show if it is posted in a remote instance
- [x] allow sorting by by content post/report time (default newest first) #87
- [x] ban person (site) should support "expires"... #97
- [ ] login: instance search list autocomplete from LV
- [x] #104

## Modlog
mod log needs a bunch of work, mainly around rendering content that was actioned.

- [ ] create views for each type of report
- [ ] ensure correct icons and action is taken _(eg. "removedPost" has "removed" attribute that could be true if it is restored)_
- [ ] need upstream api support to support "local only" filtering'

**Comment by tgxn** [comment]
reports sort:
- by report time (default newest first)
- by content post time
- oldest first
-

**Comment by tgxn** [comment]
Could maybe look at using something like https://www.npmjs.com/package/@dhaiwat10/react-link-preview
for link previews, I've just been writing my own handlers

**Comment by tgxn** [comment]
moved some to #75
