### ISSUE TITLE
Bans TODO

### ISSUE THREAD

**Issue by tgxn** [tgxn/lemmy-modder#33]
Load Site-Wide bans list, allow managing expiry, reasons etc

Also, maybe show my community-bans?

- [ ] show list of current site-wide bans 
  - [ ] when/if they expire
  - [ ] who applied them
  - [ ] reason/commentary
- [ ] show list of bans by community that you mod
  - [ ] as admin, search communities/paginated list showing mods

**Comment by tgxn** [comment]
# get / ban users
- https://join-lemmy.org/api/classes/LemmyHttp.html#getBannedPersons
- ✅ https://join-lemmy.org/api/classes/LemmyHttp.html#banFromCommunity
- ✅ https://join-lemmy.org/api/classes/LemmyHttp.html#banPerson

**Comment by tgxn** [comment]
Some ideas from https://beehaw.org/post/574562

- Ability to send warning PM to use direct from reports list
- Ability to perform multi-action (send warning, remove content and temp ban user)

**Comment by Pdzly** [comment]
getBannedPersons require admin access so far i know.

The ideas to send warning pms could be a instance standard too. So if admins want the dming HAS to be done. It should have it automatically activated or deactivated. ( could be relating to #60 )

#60 "could" enable that admins could enable the publishing of bans.

**Comment by tgxn** [comment]
can be added to #121 - listing of community bans.
